server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: Divya7@sql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

kafka:
  server: localhost:9092
  topics:
    test_topic: "kafka_testing"
